# Generated by Django 4.2.6 on 2023-10-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tweet',
            new_name='thought',
        ),
    ]
